markdown: rdiscount

title: anotherDevsRamblings
email: glenkeane.94@gmail.com
description: "This is Glen Keane's personal website for all his rants, raves and ramlings."

paginate: 10
baseurl: ""
url: "http://glenkeane.me"

permalink: pretty
relative_permalinks: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Glen Keane"

