gems:
  - jekyll-paginate

kramdown:
  input: GFM
  syntax_highlighter: rouge

title: anotherDevsRamblings
email: glenkeane.94@gmail.com
description: "This is Glen Keane's personal website for all his rants, raves and ramlings."

paginate: 10
baseurl: ""
url: "http://glenkeane.me"

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Glen Keane"
