gems:
  - jekyll-paginate

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

title: Glen Keane
email: glenkeane.94@gmail.com
description: "Senior Forward Deployed AI Engineer. Building AI-integrated solutions at Brightbeam."

paginate: 10
baseurl: ""
url: "https://glentiki.dev"

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Glen Keane"
